language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install: pip install tox-travis coveralls coverage
script:
  - tox
  - coverage report
after_success:
  - coveralls
notifications:
  email:
    recipients:
      - christopherjordan87@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
